name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # ubuntu-latest,
        # use macos-13 for intel compilation ???
        os: [macos-13, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18.17'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn

      #   - name: build-linux
      #     if: matrix.os == 'ubuntu-latest'
      #     run: sudo snap install snapcraft --classic && yarn build:linux

      - name: build-mac
        if: matrix.os == 'macos-13'
        run: sudo -H pip install setuptools && yarn build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
